schema_version = "1.0.0"
id = "gm_uvs"
version = "0.2.1"
name = "GM UVs"
tagline = "Game Makers UVs: UV tools for game artists"
maintainer = "Game Makers"
type = "add-on"
tags = ["UV"]
blender_version_min = "5.0.0"
license = ["SPDX:GPL-3.0-or-later"]

